name: cmake

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: install
        run: ./install.sh
      - name: build
        run: ./build.sh
      - name: run tests
        run: python3 test.py
      - name: create coverage report
        run: |
          sudo apt install lcov
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --remove coverage.info '*.h' --output-file coverage.info
          lcov --remove coverage.info '*test*.cc' --output-file coverage.info
          lcov --list coverage.info
          bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
