name: make

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: install
        run: ./install.sh
      - name: build
        run: ./build-gcc.sh
      - name: run tests
        run: python3 test.py -d rm,rbf

